objects/Account_Contact__c.object
<CustomObject>
    <description>Junction object linking a Contact record to an Account record.  Used so a contact can have many accounts without duplicating the contact information</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Lookup to Account object Contact is linked to.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Contacts</relationshipLabel>
        <relationshipName>Account_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Lookup to Contact linking it to an Account</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Contacts</relationshipLabel>
        <relationshipName>Account_Contacts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unique_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>GSOAccountID:GSOContactID

Used to enforce uniqueness. Cannot have the same contact associated with the same account.</description>
        <externalId>true</externalId>
        <label>Unique Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Account Contact</label>
    <nameField>
        <displayFormat>AC-{000000}</displayFormat>
        <label>Account Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Standard external contact</description>
        <label>Contact</label>
    </recordTypes>
</CustomObject>

classes/AccountContactClass_Test.cls
@isTest
private class AccountContactClass_Test {

    static testMethod void myUnitTest() {
    	Account testAccount = new Account(Name = 'TestAccount');
    	insert testAccount;
    	
    	Contact testContact = new Contact(FirstName = 'MyMethod', LastName = 'Tester', Email = 'methodtest@fakeemailaddress.bad');
    	insert testContact;
    	
        Test.startTest();
        Account_Contact__c myAccountContact = new Account_Contact__c(Account__c = testAccount.Id, Contact__c = testContact.Id);
        
        List<Account_Contact__c> allAccountContacts = new List<Account_Contact__c>();
        allAccountContacts.add(myAccountContact);        
        AccountContactClass.buildUniqueKeys(allAccountContacts);
        
        system.assertEquals(myAccountContact.Unique_Key__c, myAccountContact.Account__c + ':' + myAccountContact.Contact__c);
        insert myAccountContact;
        
        allAccountContacts = AccountContactClass.findByAccountId(testAccount.Id);
        
        Set<String> testEmails = new Set<String>{testContact.email};
        
        AccountContactClass acObj = new AccountContactClass();        
        acObj.getEmailToListOfAccountContacts(allAccountContacts);
        acObj.getAllByContactEmail(testEmails);
        acObj.getEmailCountsForEmails(testEmails);        
        Test.stopTest();
    }
}