objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Venere property</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Destination_Services</fullName>
        <active>true</active>
        <description>Represents a destination services vendor</description>
        <label>Destination Services</label>
    </recordTypes>
    <recordTypes>
        <fullName>Hotel</fullName>
        <active>true</active>
        <description>Represents a hotel or property on an Expedia Inc point of sale</description>
        <label>Hotel</label>
    </recordTypes>
</CustomObject>

objects/Contract_Checklist__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contract Checklists</relationshipLabel>
        <relationshipName>Contract_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Complete_Date__c</fullName>
        <label>Contract Complete Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Contract_Start_Loading_Date__c</fullName>
        <label>Contract Start Loading Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_ID_Requested__c</fullName>
        <label>Date ID Requested</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_MM_Notified__c</fullName>
        <label>Date MM Notified</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_Returned_to_Loading_Team_From_MM_MC__c</fullName>
        <label>Date Returned to Loading Team From MM/MC</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_Returned_to_MM_MC__c</fullName>
        <description>Date contract loading had to ask a question of MM/MC about loading a contract.</description>
        <label>Date Returned to MM/MC</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Docusign_Mail_Received_Date__c</fullName>
        <label>Docusign Mail Received Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PSG_Checklist_Created_By__c</fullName>
        <description>Lookup to User that created checklist in PSG Salesforce</description>
        <label>PSG Checklist Created By</label>
        <referenceTo>PSG_User__c</referenceTo>
        <relationshipLabel>Contract Checklists</relationshipLabel>
        <relationshipName>Contract_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSG_RecordType__c</fullName>
        <description>The PSG RecordType so we can set the GSO RecordType</description>
        <label>PSG RecordType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rejected_Date__c</fullName>
        <label>Rejected Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Rejected_Return_to_Loading_Date__c</fullName>
        <label>Rejected Return to Loading Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Set_up_EVC__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates to if hotel is to be set up with EVC.</description>
        <inlineHelpText>Check this box if you want the hotel to be set up with EVC (Expedia Virtual Card).</inlineHelpText>
        <label>Set up EVC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Set_up_Expedia_Pay__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field indicates if a property is to be set up on Expedia pay</description>
        <inlineHelpText>Check this box if you want the hotel to be set up with an Expedia Pay account.</inlineHelpText>
        <label>Set up Expedia Pay</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Approval Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Load - Rate Sheet Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Load - Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Returned to MM/MC-See Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Returned to Loading Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected - Returned to Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requested ID&apos;s(Vendor or Expedia ID)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loading Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Ready for QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Loading Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional Inventory Load - Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Load Additional Inventory</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contract Checklist</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Contract Checklist Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Checklists</pluralLabel>
    <recordTypes>
        <fullName>Destination_Services</fullName>
        <active>true</active>
        <description>Contract Checklist for a Destination Services contract</description>
        <label>Destination Services</label>
    </recordTypes>
    <recordTypes>
        <fullName>Hotel</fullName>
        <active>true</active>
        <description>Contract Checklist for a Hotel</description>
        <label>Hotel</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/External_Logins__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Stores Logins  for external systems</description>
    <fields>
        <fullName>Password__c</fullName>
        <description>password from external system</description>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>username for external system</description>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>External Logins</label>
</CustomObject>

classes/ContractChecklistClass.cls
public with sharing class ContractChecklistClass {
	
	Private Map<String,RecordType> recordTypesMap = Utilities.getRecordTypesMap('Contract_Checklist__c', true);
	
	public static Boolean informaticaRunning = false;
	
	public static Contract_Checklist__c findById(Id contractChecklistId) {
		
		return [SELECT Id
                  ,Account__c
                  ,Status__c
                  ,PSG_Checklist_Created_By__c
				  ,Account__r.Name
				  ,Set_up_EVC__c
				  ,Set_up_Expedia_Pay__c 
              FROM Contract_Checklist__c
             WHERE Id = :contractChecklistId
             LIMIT 1];
	}
	
	public static List<Contract_Checklist__c> findByIds(Set<Id> checklistIds) {
	  return [SELECT Id
	                ,Account__c
                  ,Status__c
              FROM Contract_Checklist__c
             WHERE Id IN :checklistIds];	
	}
	
	public static void RunInformatica() {
		if (ContractChecklistClass.informaticaRunning == false) {
			ContractChecklistClass.informaticaRunning = true;
		  External_Logins__c login = External_Logins__c.getInstance('informatica_cloud');
  
      if(login != null) {
        //system.debug('INFORMATICA TRIGGERED=' + informaticaTriggered);
        InformaticaCloud.runJob(login.UserName__c,login.Password__c,'CL-Contract-ID-Update-GSO-PSG','DSS');  
        //informaticaTriggered = true;
      }	
		}
	} 
    
  public void statusChanged(List<Contract_Checklist__c> changedStatuses){
    ContractLoadingStepClass objStep = new ContractLoadingStepClass();
    objStep.newContractLoadingSteps(changedStatuses);
   
  }
  
  public void ContractReturnedToMMDate(List<Contract_Checklist__c> checklists) {
  	
  	for (Contract_Checklist__c checklist : checklists) {
  		if (checklist.Date_Returned_to_MM_MC__c == null && 
  		    ContractReturnedToMM(checklist.Status__c) == true &&
  		    checklist.RecordTypeId == recordTypesMap.get('Hotel').Id ) {
  		  checklist.Date_Returned_to_MM_MC__c = datetime.now();
  		}
  	}
  }
  
  public void ContractReturnedToLoadingTeam(List<Contract_Checklist__c> checklists) {
  	 
    for (Contract_Checklist__c checklist : checklists) {
      if (checklist.Date_Returned_to_Loading_Team_From_MM_MC__c == null && 
           ContractReturnedToLoadingTeam(checklist.Status__c) == true &&
           checklist.RecordTypeId == recordTypesMap.get('Hotel').Id ) {
         checklist.Date_Returned_to_Loading_Team_From_MM_MC__c = datetime.now();
       }	
    }
  }
  
  public void ContractRejectedReturnedToLoading(List<Contract_Checklist__c> checklists) {
     
    for (Contract_Checklist__c checklist : checklists) {
      if (checklist.Rejected_Return_to_Loading_Date__c == null && 
           ContractRejectedReturnedToLoading(checklist.Status__c) == true &&
           checklist.RecordTypeId == recordTypesMap.get('Hotel').Id ) {
         checklist.Rejected_Return_to_Loading_Date__c = datetime.now();
       }  
    }
  }
  
  public void ContractRejected(List<Contract_Checklist__c> checklists) {
     
    for (Contract_Checklist__c checklist : checklists) {
      if (checklist.Rejected_Date__c == null && 
           ContractRejected(checklist.Status__c) == true &&
           checklist.RecordTypeId == recordTypesMap.get('Hotel').Id ) {
         checklist.Rejected_Date__c = datetime.now();
       }  
    }
  }
  
  public void ContractLoadingComplete(List<Contract_Checklist__c> checklists) {
     
    for (Contract_Checklist__c checklist : checklists) {
      if (ContractLoadingComplete(checklist.Status__c) == true) {
      	if (checklist.Contract_Complete_Date__c == null) {
      	  checklist.Contract_Complete_Date__c = datetime.now();	
      	}
      	if (checklist.RecordTypeId == recordTypesMap.get('Hotel').Id &&
      	    checklist.Date_MM_Notified__c == null) {
      	  checklist.Date_MM_Notified__c = datetime.now();
      	}
      }     
    }  
  } 
  
  public void DocusignMailRecievedDate(List<Contract_Checklist__c> checklists) {
  	for (Contract_Checklist__c checklist : checklists) {
  		if (checklist.Docusign_Mail_Received_Date__c != null &&
  		    checklist.Contract_Start_Loading_Date__c == null &&
  		    checklist.RecordTypeId == recordTypesMap.get('Hotel').Id) {
  		  checklist.Contract_Start_Loading_Date__c = datetime.now();
  		}
  	} 
  }
  public void DateIdRequested(List<Contract_Checklist__c> checklists) {
    for (Contract_Checklist__c checklist : checklists) {
      if (RequestedIDs(checklist.Status__c) == true &&
          checklist.Date_ID_Requested__c == null) {
        checklist.Date_ID_Requested__c = datetime.now();
      }
    } 	
  	
  }
  public void updateContractChecklistStatus(Set<Id> checklistIds,String status) {
        
    List<Contract_Checklist__c> checklists = ContractChecklistClass.findByIds(checklistIds);
                                                  
    for(Contract_Checklist__c checklist : checklists) {
      checklist.Status__c = status;
    }
        
    update checklists;
  }
  
  public void AssignValuesBeforeInsert(List<Contract_Checklist__c> checklists) {
    for(Contract_Checklist__c checklist : checklists) {
    	if (DestinationServicesChecklist(checklist.PSG_RecordType__c)) {
    		checklist.RecordTypeId = recordTypesMap.get('Destination_Services').Id;
    		checklist.Contract_Start_Loading_Date__c = datetime.now();
    	}
    	
    	if (HotelChecklist(checklist.PSG_RecordType__c)) {
    		checklist.RecordTypeId = recordTypesMap.get('Hotel').Id;
    	}
    }	
  }
  
  private Boolean DestinationServicesChecklist(String psgRecordType) {
    return psgRecordType == 'Destination_Services_Checklist';	
  }
  
  private Boolean HotelChecklist(String psgRecordType) {
  	return psgRecordType == 'New2007ContractRecordType';
  }
  
  private Boolean ContractReturnedToMM(String status) {
    return status == 'Contract Returned to MM/MC-See Comments';
  }
  
  private Boolean ContractReturnedToLoadingTeam(String Status) {
  	return status == 'Contract Returned to Loading Team';
  }
  
  private Boolean ContractLoadingComplete(String status) {
    return status == 'Contract Loading Complete';
  }
  
  private Boolean ContractRejectedReturnedToLoading(String status) {
  	return status == 'Rejected - Returned to Loading';
  }
  
  private Boolean ContractRejected(String status) {
  	return status == 'Rejected';
  }
  
  private Boolean RequestedIDs(String status) {
  	return status == 'Requested ID\'s(Vendor or Expedia ID)';
  }
  
  private Boolean LoadingContract(String status) {
  	return status == 'Loading Contract';
  }
}