objects/Account.object
<CustomObject>
    <fields>
        <fullName>External_Account_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Salesforce Account.Id field from the PSG Org.  Needed for integration bewteen GSO and PSG Orgs</description>
        <externalId>true</externalId>
        <label>External Account Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Venere property</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

objects/Connection__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Connections</relationshipLabel>
        <relationshipName>Connections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Connectivity_System__c</fullName>
        <label>Connectivity System</label>
        <referenceTo>Connectivity_System__c</referenceTo>
        <relationshipLabel>Connections</relationshipLabel>
        <relationshipName>Connections</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Integration_Connection_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Integration Connection Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <picklist>
            <picklistValues>
                <fullName>EQC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Displays the highest rollout step. Can be manually overridden.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Connecting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrollment Form Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Enrollment Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Enrollment Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Enrollment Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrollment Form Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mapping Information Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Mapping Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Mapping Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Mapping Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mapping Confirmation Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Soft Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disconnected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Connection</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Connection Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Connectivity_System__c.object
<CustomObject>
    <label>Connectivity System</label>
    <nameField>
        <label>Connectivity System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connectivity Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ConnectionClass_Test.cls
@isTest
private class ConnectionClass_Test {

    static testMethod void myUnitTest() {
    	//hardcoding fake AccountId for test;
    	String psgAccountId = 'TEST000000d8XlEAAU';
        Account myAccount = new Account (Name='PSG Test', External_Account_Id__c = psgAccountId);
        insert myAccount;
        
		Connectivity_System__c myConnectivitySystem = new Connectivity_System__c (Name = 'TestConnectivitySystem');
		insert myConnectivitySystem;
		
		Connection__c myConnection = new Connection__c (Account__c = myAccount.Id
													   ,Connectivity_System__c = myConnectivitySystem.Id
													   ,Type__c = 'Type'
													   ,Status__c = 'Connected'
													   ,Platform__c = 'Platform');
													   
		insert myConnection;		
		
		//requery to get formula field
		myConnection = ConnectionClass.getConnection(myConnection.Id);
		
		List<Connection__c> myConnections = new List<Connection__c>();
		myConnections.add(myConnection);
		
		ConnectionClass conObj = new ConnectionClass();
		conObj.buildConnectionIntegrationKeys(myConnections, null);		
		
		system.assertEquals(psgAccountId+ ':' + myConnection.Type__c + ':' + myConnection.Platform__c, myConnection.Integration_Connection_Key__c);
		
		
		myConnections = ConnectionClass.getConnectionsByAccountId(myAccount.Id);
		system.assertEquals(myConnections.size(), 1);
		
		myConnection.Type__c = 'CHANGED';
		ConnectionClass.upsertConnection(myConnection);		
		myConnection = ConnectionClass.getConnection(myConnection.Id);		
		system.assertEquals(myConnection.Type__c, 'CHANGED');
		
		conObj.deleteConnectionIntegrationKeys(myConnections);
		
		myConnection = new Connection__c (Account__c = myAccount.Id
										 ,Connectivity_System__c = myConnectivitySystem.Id
										 ,Type__c = 'New'
										 ,Status__c = 'Disconnected'
										 ,Platform__c = 'Insert');
		
		ConnectionClass.upsertConnection(myConnection);
		
		
										 		   
    }
}