objects/Account.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <description>Brand hotels rolls up to</description>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Chain__c</fullName>
        <description>Chain property rolls up to</description>
        <label>Chain</label>
        <referenceTo>Chain__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Closest_Airport__c</fullName>
        <description>Airport Code for nearest airport</description>
        <label>Closest Airport</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESR_Structure_Type__c</fullName>
        <description>Lookup to Structure Type for Property at ESR level</description>
        <label>ESR Structure Type</label>
        <referenceTo>Structure_Type__c</referenceTo>
        <relationshipLabel>Accounts (ESR Structure Types)</relationshipLabel>
        <relationshipName>ESR_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expedia_Hotel_Id__c</fullName>
        <description>Id that is unique identifier in Lodging Catalog Master database</description>
        <label>Expedia Hotel Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price_Level__c</fullName>
        <description>From PSG Salesforce.  Price level of property</description>
        <label>Price Level</label>
        <picklist>
            <picklistValues>
                <fullName>Lower Tier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle Tier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upper Tier</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Venere property</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Structure_Type__c</fullName>
        <label>Structure Type</label>
        <picklist>
            <picklistValues>
                <fullName>All-inclusive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apart - Hotel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apartment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bed &amp; Breakfast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cabin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chalet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Condo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Condominium resort</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cottage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guest House</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hostel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotel resort</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotel-unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>House boat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lodge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Motel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Overwater Accommodation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Vacation Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ranch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ryokan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tree house</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Villa</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submarket__c</fullName>
        <description>Looks up to the submarket the account belongs to</description>
        <label>Submarket</label>
        <referenceTo>Submarket__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Super_Region__c</fullName>
        <label>Super Region</label>
        <referenceTo>Super_Region__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_Id__c</fullName>
        <description>Contains the Vendor Id for a property</description>
        <label>Vendor Id</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Hotel</fullName>
        <active>true</active>
        <description>Represents a hotel or property on an Expedia Inc point of sale</description>
        <label>Hotel</label>
    </recordTypes>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Additional_Information__c</fullName>
        <description>Used to store additional information from a case. Can be used as a merge field on an email template.</description>
        <label>Additional Information</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <description>A list to choose Expedia.com (E*), Hotels.com (H*), or both</description>
        <label>Brand</label>
        <picklist>
            <picklistValues>
                <fullName>E*</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Egencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>H*</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Venere</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Both</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Chain__c</fullName>
        <label>Chain</label>
        <referenceTo>Chain__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ids_Requested__c</fullName>
        <description>Used to indicate the types of IDs requested when an ID creation case is created (based on the current ID values for the account).</description>
        <label>Ids Requested</label>
        <picklist>
            <picklistValues>
                <fullName>Expedia Hotel ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expedia Vendor ID</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Super_Region__c</fullName>
        <label>Super Region</label>
        <picklist>
            <picklistValues>
                <fullName>Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LATAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vendor_ID__c</fullName>
        <formula>Account.Vendor_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vendor ID</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Id_Request</fullName>
        <active>true</active>
        <businessProcess>Id Request</businessProcess>
        <description>For requesting expedia or other id types from the content group. Part of contract workflow.</description>
        <label>Id Request</label>
    </recordTypes>
</CustomObject>

objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Standard external contact</description>
        <label>Contact</label>
    </recordTypes>
</CustomObject>

objects/Contract_Checklist__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contract Checklists</relationshipLabel>
        <relationshipName>Contract_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Set_up_EVC__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates to if hotel is to be set up with EVC.</description>
        <inlineHelpText>Check this box if you want the hotel to be set up with EVC (Expedia Virtual Card).</inlineHelpText>
        <label>Set up EVC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Set_up_Expedia_Pay__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field indicates if a property is to be set up on Expedia pay</description>
        <inlineHelpText>Check this box if you want the hotel to be set up with an Expedia Pay account.</inlineHelpText>
        <label>Set up Expedia Pay</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Approval Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Load - Rate Sheet Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Load - Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Returned to MM/MC-See Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Returned to Loading Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected - Returned to Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requested ID&apos;s(Vendor or Expedia ID)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loading Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Ready for QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Loading Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional Inventory Load - Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Load Additional Inventory</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contract Checklist</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Contract Checklist Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Checklists</pluralLabel>
    <recordTypes>
        <fullName>Hotel</fullName>
        <active>true</active>
        <description>Contract Checklist for a Hotel</description>
        <label>Hotel</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>Maps the region the market belongs to</description>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Markets</relationshipLabel>
        <relationshipName>Markets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Super_Region__c</fullName>
        <formula>Region__r.Super_Region__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Super Region</label>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Region account resides in</description>
    <fields>
        <fullName>Super_Region__c</fullName>
        <description>Super region the regions maps to</description>
        <label>Super Region</label>
        <referenceTo>Super_Region__c</referenceTo>
        <relationshipLabel>Regions</relationshipLabel>
        <relationshipName>Regions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EIDRequestExtension.cls
public class EIDRequestExtension {

        private final String CASE_SOBJECT_TYPE = 'Case';
        private final String CASE_RECORD_TYPE = 'Id_Request';
        private final String CASE_SUBJECT = 'Expedia Id Request';

        public Contract_Checklist__c ContractChecklist {get; set;}
        public String UserComments{get;set;}
        public String AccountName {get;set;}
        public String Phone {get;set;}
        public String Chain {get;set;}
        public String Fax {get;set;}
        public String Brand {get;set;}
        public String StructureType {get;set;}
        public String PriceLevel {get;set;}
        public String SuperRegion {get;set;}
        public String Region {get;set;}
        public String Market {get;set;}
        public String Submarket {get;set;}
        public String ClosestAirport {get;set;}
        public String BillingStreet {get;set;}
        public String BillingCity {get;set;}
        public String BillingState {get;set;}
        public String BillingPostalCode {get;set;}
        public String BillingCountry {get;set;}
        public Boolean InvalidInput {get;set;}
        public String IdsRequested {get;set;}
        
    public EIDRequestExtension() {
    	try {
	    	Id contractChecklistId = Apexpages.currentPage().getParameters().get('Id');
	        Contract_Checklist__c objChecklist = ContractChecklistClass.findById(contractChecklistId);
        										 
	    	this.ContractChecklist = objChecklist;
	        this.UserComments = this.PrePopulateComments();
	        this.InitializeFields();
		}catch(Exception ex) {
			Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'No contract checklist found. Please contact support at <a href="mailto:gsosfsup@expedia.com">gsosfsup@expedia.com.</a>'));
		}
    }
    
    public PageReference Save() {
        try {
            // create a case
            if(!ValidInput()){
                InvalidInput = true;
            }else {
                    Case objCase = this.CreateCase();
                    
                    // redirect to case
                    return new ApexPages.StandardController(objCase).view();
            }
        }catch(Exception ex) {
            system.debug(ex.getMessage());
            Apexpages.addMessage(new Apexpages.Message(Apexpages.Severity.ERROR, ex.getMessage()));
        }
        
        return Apexpages.currentPage();
    }
    
    public PageReference Cancel() {
        //update contract checklist
        this.ContractChecklist.Status__c = 'Expedia Hotel ID request cancelled';
        update this.ContractChecklist;
        
        // redirect to contract checklist
        return new ApexPages.StandardController(this.ContractChecklist).view();
        
    }
    
    public List<SelectOption> getStructureTypes() {
        List<SelectOption> options = new List<SelectOption>();
        
        for(Structure_Type__c structType : [Select Id, Name From Structure_Type__c order by Name]) {
            options.add(new SelectOption(structType.Name, structType.Name));
        }
        
        return options;
    }
    
    /////////// Private Methods

    private Case CreateCase() {
        Case objCase = new Case(); 
        objCase.RecordTypeId = this.GetCaseRecordType().Id; 
        objCase.AccountId = this.ContractChecklist.Account__c; 
        objCase.Subject = CASE_SUBJECT; 
        objCase.SuppliedPhone = this.Phone;
        objCase.Description = this.UserComments; 
        objCase.Additional_Information__c = this.GetRequest();
        objCase.Type = 'Account Management';
        objCase.Origin = 'MM';
        objCase.Ids_Requested__c = this.IdsRequested;
        
		database.DMLOptions dmo = new database.DMLOptions();
        
		AssignmentRule[] ar = [SELECT Id 
                               FROM AssignmentRule 
                              WHERE Active = True];
                               
		if(ar.size() != 0) {
			dmo.AssignmentRuleHeader.assignmentRuleId = ar[0].Id;
		}
      
		dmo.AssignmentRuleHeader.useDefaultRule = false;
		objCase.setOptions(dmo);

        insert objCase;
        
        return objCase;
    }
        
    private RecordType GetCaseRecordType() {
        return [Select Id From RecordType Where SObjectType = : CASE_SOBJECT_TYPE and DeveloperName = : CASE_RECORD_TYPE limit 1];
    }
        
    private String PrePopulateComments() {
        // Added to prepopulate comments with a note to setup Expedia Pay 
        // and/or EVC to pass on to case. Used this method instead of creating 
        // new fields on case object. 
        String comments;
        
        if ((this.ContractChecklist.Set_up_Expedia_Pay__c == true) || (this.ContractChecklist.Set_up_EVC__c == true)) { 
            comments = 'NOTE:';
            
            if (this.ContractChecklist.Set_up_Expedia_Pay__c == true) { 
                comments += ' Need to set up Expedia Pay.'; 
            } 
            
            if (this.ContractChecklist.Set_up_EVC__c == true) { 
                comments += ' Need to set up EVC.'; 
            } 
        }// END
        
        return comments; 
    }
        
    private String GetRequest() {
        String strRequest;
        
        strRequest = 'Account Name: ' + this.AccountName + '\n';
        strRequest += 'Phone: ' + this.Phone + '\n';
        strRequest += 'Fax: ' + this.Fax + '\n';
        strRequest += 'Billing Street: ' + this.BillingStreet + '\n';
        strRequest += 'Billing City: ' + this.BillingCity + '\n';
        strRequest += 'Billing State/Province: ' + this.BillingState + '\n';
        strRequest += 'Billing Zip/Postal Code: ' + this.BillingPostalCode + '\n';
        strRequest += 'Billing Country: ' + this.BillingCountry + '\n';
        strRequest += 'Chain: ' + this.Chain + '\n';
        strRequest += 'Brand: ' + this.Brand + '\n';
        strRequest += 'Structure Type: ' + this.StructureType + '\n';
        strRequest += 'Price Level: ' + this.PriceLevel + '\n';
        strRequest += 'Super Region: ' + this.SuperRegion + '\n';
        strRequest += 'Region: ' + this.Region + '\n';
        strRequest += 'Market: ' + this.Market + '\n';
        strRequest += 'Submarket: ' + this.Submarket + '\n';
        strRequest += 'Closest Airport: ' + this.ClosestAirport + '\n';
        strRequest += 'Ids Requested: ' + this.IdsRequested + '\n';
        
        return strRequest;
    }       
        
    private void InitializeFields() {
        InvalidInput = false;
        
        if(this.ContractChecklist.Account__c != NULL) {
                /*String fields = 'Name,Phone,Fax,BillingStreet,BillingCity,BillingState,BillingPostalCode,BillingCountry,Chain__r.Name,Brand__r.Name,ESR_Structure_Type__r.Name,Structure_Type__c,Price_Level__c,Super_Region__r.Name,Region__r.Name,Market__r.Name,Submarket__r.Name,Closest_Airport__c,Expedia_Hotel_Id__c,Vendor_Id__c';
                List<SoqlBuilder.Condition> conditions = new List<SoqlBuilder.Condition>{new SoqlBuilder.Condition('Id', this.objContractChecklist.Account__c)};
                List<Account> accounts = (List<Account>)SoqlBuilder.ExecuteSelectQuery(fields,'Account',conditions, null, null);
                */
                
                List<Account> accounts = [Select Name,
                								 Phone,
                								 Fax,
                								 BillingStreet,
                								 BillingCity,
                								 BillingState,
                								 BillingPostalCode,
                								 BillingCountry,
                								 Chain__r.Name,
                								 Brand__r.Name,
                								 ESR_Structure_Type__r.Name,
                								 Price_Level__c,
                								 Super_Region__r.Name,
                								 Region__r.Name,
                								 Market__r.Name,
                								 Submarket__r.Name,
                								 Closest_Airport__c,
                								 Expedia_Hotel_Id__c,
                								 Vendor_Id__c
                								 From Account
                								 Where Id = : this.ContractChecklist.Account__c]; 
                
                for(Account acct : accounts) {
                this.AccountName = acct.Name;
                this.Phone = acct.Phone;
                this.Fax = acct.Fax;
                this.BillingStreet = acct.BillingStreet;
                this.BillingCity = acct.BillingCity;
                this.BillingState = acct.BillingState;
                this.BillingPostalCode = acct.BillingPostalCode;
                this.BillingCountry = acct.BillingCountry;
                this.Chain = acct.Chain__r.Name;
                this.Brand = acct.Brand__r.Name;
                this.StructureType = acct.ESR_Structure_Type__r.Name;
                this.PriceLevel = acct.Price_Level__c;
                this.SuperRegion = acct.Super_Region__r.Name;
                this.Region = acct.Region__r.Name;
                this.Market = acct.Market__r.Name;
                this.Submarket = acct.Submarket__r.Name;
                this.ClosestAirport = acct.Closest_Airport__c;
                this.IdsRequested = getRequestType(acct.Expedia_Hotel_Id__c , acct.Vendor_Id__c);
                }
        }else {
            this.IdsRequested = getRequestType(null, null);
        }
    }
    
    private Boolean ValidInput() {
        if(this.AccountName == '' || this.BillingCity == '' || this.BillingStreet == '' || this.BillingCountry == '' ||
                this.Chain == '' || this.Brand == '' || this.StructureType == '' || this.SuperRegion == '' || this.Submarket == '' ||
                this.Phone == '' || this.Fax == '' || this.ClosestAirport == ''){
                return false;
        }
        return true;
    }

    private String getRequestType(String eId, String vId) {
        String returnTypes = '';
        if (eId == null || eId == '') returnTypes += 'Expedia Hotel ID;'; 
        if (vId == null || vId == '') returnTypes += 'Expedia Vendor ID;'; 
        
        return returnTypes;
    }
}