objects/Account.object
<CustomObject>
    <fields>
        <fullName>ARI_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if property is ARI Enabled</description>
        <label>ARI Enabled?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Booking_Delivery_Method__c</fullName>
        <description>Come from PSG.  Indicates how property receives notficiations for bookings</description>
        <label>Booking Delivery Method</label>
        <picklist>
            <picklistValues>
                <fullName>Electronic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fax Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ESR_or_GDS__c</fullName>
        <label>ESR or GDS?</label>
        <picklist>
            <picklistValues>
                <fullName>ESR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GDS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Expedia_Hotel_Id__c</fullName>
        <description>Id that is unique identifier in Lodging Catalog Master database</description>
        <label>Expedia Hotel Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HIMS_Stop_Sell__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if ESR Hotels is on Stop Sell from HIMS</description>
        <label>HIMS Stop Sell</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PSG_Lead_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PSG Lead Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Super_Region__c</fullName>
        <label>Super Region</label>
        <referenceTo>Super_Region__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_Id__c</fullName>
        <description>Contains the Vendor Id for a property</description>
        <label>Vendor Id</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Venere_Contract_Status__c</fullName>
        <description>Status of the venere contracting process</description>
        <label>Venere Contract Status</label>
        <picklist>
            <picklistValues>
                <fullName>Accepted Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property Deactivated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property Reactivated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent affiliation email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent affiliation email to a properties group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signed Contract</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Venere_Status__c</fullName>
        <description>Status of the Venere property</description>
        <label>Venere Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Selling_Model__c</fullName>
        <label>Selling Model</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>EEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ESR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GDS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Super_Region__c</fullName>
        <label>Super Region</label>
        <picklist>
            <picklistValues>
                <fullName>Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LATAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vendor_ID__c</fullName>
        <formula>Account.Vendor_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vendor ID</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Star_Ratings</fullName>
        <active>true</active>
        <businessProcess>Star Ratings</businessProcess>
        <description>Star Ratings</description>
        <label>Star Ratings</label>
    </recordTypes>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Region account resides in</description>
    <fields>
        <fullName>Super_Region__c</fullName>
        <description>Super region the regions maps to</description>
        <label>Super Region</label>
        <referenceTo>Super_Region__c</referenceTo>
        <relationshipLabel>Regions</relationshipLabel>
        <relationshipName>Regions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Star_Rating_Review__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Star_Ratings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Case_Number__c</fullName>
        <label>Case Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Star_Ratings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Star Rating Review</label>
    <nameField>
        <displayFormat>SR-{00000}</displayFormat>
        <label>Star Ratings Review ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Star Rating Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AccountClass.cls
public with sharing class AccountClass {
	
	public List<Account> FindAllById(Set<Id> accountIds) {
		
		List<Account> accounts = new List<Account>();
		
		accounts = [SELECT Id
		                  ,Name
		                  ,Expedia_Hotel_Id__c
		                  ,Vendor_Id__c
		                  ,Region__r.Name
		                  ,Booking_Delivery_Method__c
		                  ,ARI_Enabled__c
		              FROM Account
		             WHERE Id IN :accountIds];
		             
	  return accounts;
		 
	}

	public void BeforeInsertUpdateAccount(List<Account> accounts) {
		Region__c MEXICO = RegionClass.FindRegionByName('Mexico & Central America');
		Region__c SOUTH_AMERICA = RegionClass.FindRegionByName('South America');
		Super_Region__c SUPER_REGION = SuperRegionClass.FindSuperRegionByName('LATAM');

		for(Account newAcct : accounts) {
			if(newAcct.Region__c == SOUTH_AMERICA.Id || newAcct.Region__c == MEXICO.Id) {
				// set the super region if the region field equals South America or Mexico
				newAcct.Super_Region__c = SUPER_REGION.Id;
			}else if(newAcct.Region__c == NULL && newAcct.Super_Region__c == SUPER_REGION.Id) {
				// clear the super region field if there is no value for region
				newAcct.Super_Region__c = NULL;
			}
		}
	}
	
	public void NewUnratedProperties(Map<Id, Account> oldAccounts, List<Account> newAccounts) {
		List<Case> newCases = new List<Case>();
		RecordType starRatingRecordType = [Select Id From RecordType Where DeveloperName = 'Star_Ratings' And SObjectType = 'Case' limit 1];
		// map star ratings and cases to accounts
		Map<Id, Account> acctMapping = new Map<Id,Account>([Select Id
																, (Select Id From Star_Ratings__r limit 1)
																, (Select Id From Cases Where RecordTypeId = : starRatingRecordType.Id And IsClosed = false limit 1) 
																From Account 
																Where Id IN : newAccounts]);
		
		for(Account newAccount : newAccounts) {
			
			// get old values
			Account oldAccount = (oldAccounts == null ? null : oldAccounts.get(newAccount.Id));
			Account myAccount = acctMapping.get(newAccount.Id);
			
			// verify that the account is not a lead account, does not have any star ratings or open cases
			if(myAccount.Star_Ratings__r.isEmpty() && myAccount.Cases.isEmpty() && newAccount.PSG_Lead_Account__c == false) {

				if(newAccount.ESR_or_GDS__c == 'ESR' && newAccount.Expedia_Hotel_Id__c != NULL && (oldAccounts ==  NULL || oldAccount.ESR_or_GDS__c == 'GDS')) {
					// create a star rating case if the account was a GDS account and is now an ESR account, there are no star rating reviews,
					// an EID has been created and there is no open case
					Case myCase = this.CreateCase('GDS/ESR Transition', starRatingRecordType, newAccount, 'ESR');
					newCases.add(myCase);
				}else if(newAccount.Venere_Contract_Status__c == 'Accepted Contract' && newAccount.HIMS_Stop_Sell__c == false && 
						 (newAccount.Venere_Status__c == 'Active' && oldAccount.Venere_Status__c != 'Active')) {
					// create a star rating case if the account is a Venere account the Venere Status is Active, the Venere Contract Status is
					// Accepted Contract, there are no star rating reviews, and there is no open case
					Case myCase = this.CreateCase('New Venere/EEM contract', starRatingRecordType, newAccount, 'EEM');
					newCases.add(myCase);
			 	}
			}
		}
		
		// insert cases
		if(newCases.isEmpty() == false) {
			insert newCases;
		}
	}
	
	///// Private Methods
	private Case CreateCase(String subject, RecordType starRatingRecordType, Account acct, String sellingModel) {
		return new Case(Subject = subject
                       ,RecordTypeId = starRatingRecordType.Id
                       ,Origin = 'GDS/ESR Transition'
                       ,Type = 'New Star Review'
                       ,AccountId = acct.Id
                       ,Priority = '4'
                       ,Selling_Model__c = sellingModel
                       );
	}
}