objects/Account.object
<CustomObject>
    <fields>
        <fullName>ARI_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if property is ARI Enabled</description>
        <label>ARI Enabled?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Expedia_Hotel_Id__c</fullName>
        <description>Id that is unique identifier in Lodging Catalog Master database</description>
        <label>Expedia Hotel Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

objects/EPC_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>Viewed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Date_of_Activity__c</fullName>
        <defaultValue>Now()</defaultValue>
        <label>Date of Activity</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EPC_Section__c</fullName>
        <label>EPC Section</label>
        <picklist>
            <picklistValues>
                <fullName>Commercial Terms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Form of Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Terms</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GSO_Contract__c</fullName>
        <label>GSO Contract</label>
        <referenceTo>GSOContract__c</referenceTo>
        <relationshipName>ORT_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>EPC Activity</label>
    <nameField>
        <displayFormat>EA-{0000000}</displayFormat>
        <label>EPC Activity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EPC Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GSO_Contract_Submission__c.object
<CustomObject>
    <label>GSO Contract Submission</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Submission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GSO Contract Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GSOContract__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>GSO Contracts</relationshipLabel>
        <relationshipName>GSOContracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_EPC_Completed__c</fullName>
        <description>Date EPC/ORT was marked as complete</description>
        <label>Date EPC Completed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Expedia_Hotel_Id__c</fullName>
        <formula>Account__r.Expedia_Hotel_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expedia Hotel Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GSO_Contract_Submission__c</fullName>
        <description>GSO Contract Submission</description>
        <label>GSO Contract Submission</label>
        <referenceTo>GSO_Contract_Submission__c</referenceTo>
        <relationshipLabel>GSO Contracts</relationshipLabel>
        <relationshipName>GSOContracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Setup_on_EVC__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates customer wants to be setup on EVC</description>
        <label>Setup on EVC</label>
        <type>Checkbox</type>
    </fields>
    <label>GSO Contract</label>
    <nameField>
        <displayFormat>GC-{000000}</displayFormat>
        <label>GSO Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GSO Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/GSOContractClass_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class GSOContractClass_Test {
	  
	  static testMethod void runTests() {
	  	
	  	Set<Id> gsoContractIds = new Set<Id>();
	  	Map<Id,GSOContract__c> gsoContractIdToContractMap = new Map<Id,GSOContract__c>();
      GSOContractClass objContract = new GSOContractClass();
      GSO_Contract_Submission__c submission = new GSO_Contract_Submission__c();
      insert submission;
	    
	    List<GSOContract__c> newContracts = new List<GSOContract__c>();
	   
	    for (Integer i = 0; i < 200; i++) {
	      GSOContract__c newContract = new GSOContract__c(GSO_Contract_Submission__c = submission.Id);
	      newContracts.add(newContract);		  	
	    }
	    
	    insert newContracts;
	    
	    for (GSOContract__c thisContract : newContracts) {
	    	gsoContractIds.add(thisContract.Id);
	    	gsoContractIdToContractMap.put(thisContract.Id,thisContract);
	    }
    	
    	test.startTest();
    	List<GSOContract__c> contracts = objContract.FindAllById(gsoContractIds);
    	
    	system.assertEquals(contracts.size(), 200);
    	

    }
    
    static testMethod void testUpdatePhaseAndORTEVCCases(){
    	Account testAccount = new Account();
    	
    	testAccount.ARI_Enabled__c = true;
    	testAccount.Expedia_Hotel_Id__c = 'TESTING';
    	testAccount.Name = 'SALESFORCE TEST DATA IS STUPID';
    	insert testAccount;
    	
    	Set<Id> gsoContractIds = new Set<Id>();
      Map<Id,GSOContract__c> gsoContractIdToContractMap = new Map<Id,GSOContract__c>();
      GSOContractClass objContract = new GSOContractClass();
      GSO_Contract_Submission__c submission = new GSO_Contract_Submission__c();
      insert submission;
      
      List<GSOContract__c> newContracts = new List<GSOContract__c>();
     
      for (Integer i = 0; i < 4; i++) {
        GSOContract__c newContract = new GSOContract__c(GSO_Contract_Submission__c = submission.Id,Account__c = testAccount.Id,Setup_on_EVC__c = true);
        newContracts.add(newContract);        
      }
      
      insert newContracts;
      
      for (GSOContract__c thisContract : newContracts) {
        gsoContractIds.add(thisContract.Id);
        gsoContractIdToContractMap.put(thisContract.Id,thisContract);
      }
      
      List<GSOContract__c> contracts = objContract.FindAllById(gsoContractIds);
    	
      GSOContract__c commercialContract = contracts[0];
      GSOContract__c paymentContract = contracts[1];
      GSOContract__c legalContract = contracts[2];
      
      
      
      EPC_Activity__c commercialActivity = new EPC_Activity__c(Action__c = 'Viewed'
                                                              ,Date_of_Activity__c = Date.today()
                                                              ,EPC_Section__c = 'Commercial Terms'
                                                              ,GSO_Contract__c = commercialContract.Id);
                                                              
      EPC_Activity__c paymentActivity = new EPC_Activity__c(Action__c = 'Viewed'
                                                           ,Date_of_Activity__c = Date.today()
                                                           ,EPC_Section__c = 'Payment Information'
                                                           ,GSO_Contract__c = paymentContract.Id);
                                                           
      EPC_Activity__c legalActivity = new EPC_Activity__c(Action__c = 'Viewed'
                                                         ,Date_of_Activity__c = Date.today()
                                                         ,EPC_Section__c = 'Legal Terms'
                                                         ,GSO_Contract__c = legalContract.Id);
      
      
      
      //Commercial Contract
      insert commercialActivity;
      insert paymentActivity;
      insert legalActivity;  
      
      legalContract = [SELECT Id,Date_EPC_Completed__c FROM GSOContract__c WHERE Id = :legalContract.Id];
      legalContract.Date_EPC_Completed__c = Date.today();
      update legalContract;
    	
    }
    
    static testMethod void myUnitTest() {
    	// create submission
    	GSO_Contract_Submission__c submission = new GSO_Contract_Submission__c();
    	insert submission;
    	
    	// create contract
    	GSOContract__c[] contracts = new GSOContract__c[] {
    		new GSOContract__c(GSO_Contract_Submission__c= submission.Id),
    		new GSOContract__c(GSO_Contract_Submission__c= submission.Id),
    		new GSOContract__c(GSO_Contract_Submission__c= submission.Id)
    	};
    	insert contracts;
    	
    	test.startTest();
    	
    	List<GSOContract__c> results = GSOContractClass.findBySubmissionId(submission.Id);
    	system.assertEquals(results.size(), contracts.size());
    	
    	test.stopTest();
    }
}