objects/Account.object
<CustomObject>
    <fields>
        <fullName>Expedia_Hotel_Id__c</fullName>
        <description>Id that is unique identifier in Lodging Catalog Master database</description>
        <label>Expedia Hotel Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Venere property</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vendor_Id__c</fullName>
        <description>Contains the Vendor Id for a property</description>
        <label>Vendor Id</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Hotel</fullName>
        <active>true</active>
        <description>Represents a hotel or property on an Expedia Inc point of sale</description>
        <label>Hotel</label>
    </recordTypes>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Vendor_ID__c</fullName>
        <formula>Account.Vendor_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vendor ID</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Id_Request</fullName>
        <active>true</active>
        <businessProcess>Id Request</businessProcess>
        <description>For requesting expedia or other id types from the content group. Part of contract workflow.</description>
        <label>Id Request</label>
    </recordTypes>
</CustomObject>

objects/Contract_Checklist__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contract Checklists</relationshipLabel>
        <relationshipName>Contract_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Approval Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Load - Rate Sheet Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Load - Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Returned to MM/MC-See Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Returned to Loading Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected - Returned to Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requested ID&apos;s(Vendor or Expedia ID)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loading Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Ready for QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Loading Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional Inventory Load - Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Load Additional Inventory</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contract Checklist</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Contract Checklist Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Checklists</pluralLabel>
    <recordTypes>
        <fullName>Hotel</fullName>
        <active>true</active>
        <description>Contract Checklist for a Hotel</description>
        <label>Hotel</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ContractChecklistExtension.cls
public class ContractChecklistExtension {

	private final Contract_Checklist__c objContractChecklist;
	private final String REQUEST_IDS = 'Requested ID\'s(Vendor or Expedia ID)';
	private final String CASE_SOBJECT_TYPE = 'Case';
	private final String CASE_RECORD_TYPE = 'Id_Request';
	
	public String RedirectUrl { get; set; }
	
    public ContractChecklistExtension(ApexPages.StandardController controller) {
		this.objContractChecklist = (Contract_Checklist__c)controller.getRecord();
    }
	
	public PageReference EIDRequestRedirect() {
		Pagereference objPage = Apexpages.currentPage();
		RedirectUrl = '';
		
		System.debug('>>>>>> ContractChecklistExtension.EIDRequestRedirect Status = ' + this.objContractChecklist.Status__c);
		System.debug('>>>>>> ContractChecklistExtension.EIDRequestRedirect Vendor Id = ' + this.objContractChecklist.Account__r.Vendor_Id__c);
		System.debug('>>>>>> ContractChecklistExtension.EIDRequestRedirect Expedia Hotel Id = ' + this.objContractChecklist.Account__r.Expedia_Hotel_Id__c);
		system.debug('>>>>>>>> ContractChecklistExtension.CaseSubmitted case submitted = ' + this.CaseSubmitted());
		
		if(this.objContractChecklist.Status__c == REQUEST_IDS 
		  && (this.objContractChecklist.Account__r.Vendor_Id__c == NULL 
		  || this.objContractChecklist.Account__r.Expedia_Hotel_Id__c == NULL)
		  && this.CaseSubmitted() == false) {

			// redirect to 
			objPage = Page.EIDRequest; 
			objPage.getParameters().put('Id', this.objContractChecklist.Id);
			RedirectUrl = objPage.getUrl();
		}
		
		return null;
	}
	
	///////// Private Methods
	private Boolean CaseSubmitted() {
		RecordType rtCase = this.GetCaseRecordType();
		system.debug('>>>>>>>> ContractChecklistExtension.CaseSubmitted case record type = ' + rtCase.Id);
		system.debug('>>>>>>>> ContractChecklistExtension.CaseSubmitted case account id = ' + this.objContractChecklist.Account__c);
		
		List<Case> objCase = [Select Id, CaseNumber FROM Case WHERE RecordTypeId = : rtCase.Id AND IsClosed = false AND AccountId = : this.objContractChecklist.Account__c LIMIT 1];
		return (objCase.isEmpty() == false);
	}

	private RecordType GetCaseRecordType() {
		return [Select Id From RecordType Where SObjectType = : CASE_SOBJECT_TYPE and DeveloperName = : CASE_RECORD_TYPE limit 1];
	}
}