objects/Account.object
<CustomObject>
    <fields>
        <fullName>Market_Manager_Name__c</fullName>
        <description>Name for Market Manager (Account Owner) from PSG Salesforce</description>
        <inlineHelpText>This is the Account Owner from PSG Salesforce</inlineHelpText>
        <label>Market Manager Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Accounting/Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alternative Reservations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant General Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E-Commerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EQC Hotel Vendor Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expedia Quick Connect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Franchise Service Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Front Desk Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Front Office Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guest Services Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health &amp; Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IHG Primary Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary Content Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reservations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tech Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Venere Connect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Venere Connect Hotel Vendor Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visa Support</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Standard external contact</description>
        <label>Contact</label>
    </recordTypes>
</CustomObject>

objects/GSOContract__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>GSO Contracts</relationshipLabel>
        <relationshipName>GSOContracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GSO Contract</label>
    <nameField>
        <displayFormat>GC-{000000}</displayFormat>
        <label>GSO Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GSO Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PSG_User__c.object
<CustomObject>
    <description>List of Users who are active in PSG and not active in GSO who need to share information with GSO Users.</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ReContracting_Token__c</fullName>
        <description>Token used to authenticate user</description>
        <label>ReContracting Token</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>PSG User</label>
    <nameField>
        <label>PSG User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PSG Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PSG_User_Role__c.object
<CustomObject>
    <description>Junction between PSG Users and Accounts</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>PSG User Roles</relationshipLabel>
        <relationshipName>PSG_User_Roles_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSG_User__c</fullName>
        <label>PSG User</label>
        <referenceTo>PSG_User__c</referenceTo>
        <relationshipLabel>PSG User Roles</relationshipLabel>
        <relationshipName>PSG_User_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Market Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional VP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revenue Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Line Managers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recontracting Approver</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PSG User Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSG User Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Term__c.object
<CustomObject>
    <description>Commercial Terms for re-contracting</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Commercial Term Description</description>
        <inlineHelpText>Commercial Term Description</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>Date that the commercial term is active</description>
        <inlineHelpText>Date that the commercial term is active</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Term</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Term Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/sitesVFReContracting_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class sitesVFReContracting_Test {

    static testMethod void myUnitTest() {
        // create user
        PSG_User__c psgUser = new PSG_User__c();
        
        psgUser.Email__c = 'test@test.com';
        psgUser.Name = 'Joe User';
        
        insert psgUser;
        
        // create account
        Account myAccount = new Account();
        myAccount.Name = 'Test Account';
        myAccount.Market_Manager_Name__c = psgUser.Name;
        
        insert myAccount;
        
        // create psg user role
        PSG_User_Role__c role = new PSG_User_Role__c();
        role.Account__c = myAccount.Id;
        role.PSG_User__c = psgUser.Id;
        role.Role__c = 'Market Coordinator';
        
        insert role;
        
        // create contact
        Contact myContact = new Contact();
        myContact.FirstName = 'Jill';
        myContact.LastName = 'User';
        myContact.AccountId = myAccount.Id;
        
        insert myContact; 
        
        // create terms
        Term__c myTerm = new Term__c();
        myTerm.Description__c = 'Contract Length (months)';
        myTerm.Start_Date__c = System.today();
        
        insert myTerm;
        
        // authenticate the user
        ReContractingAuthentication authentication = new ReContractingAuthentication();
        authentication.PSGUserEmail = psgUser.Email__c;
        authentication.RequestAuthentication();
        
        // get recontracting token
        psgUser = PSGUserClass.findByEmail(psgUser.Email__c);
        System.assertNotEquals(psgUser.ReContracting_Token__c, null);
        Apexpages.currentPage().getParameters().put('mm', psgUser.Email__c);
        Apexpages.currentPage().getParameters().put('token', psgUser.ReContracting_Token__c);
        authentication.VerifyAuthentication();

        test.startTest();
        
        sitesVFReContracting controller = new sitesVFReContracting();
        system.assertEquals(controller.PSGUser.ReContracting_Token__c, psgUser.ReContracting_Token__c);
        
        // verify that the user has been authenticated
        PageReference pRef = controller.VerifyAuthentication();
        system.assertEquals(pRef, null);
        
        // get available accounts
        List<sitesVFReContracting.AccountWrapper> accounts = controller.AvailableAccounts;
        system.assertNotEquals(accounts.isEmpty(), true);
        
        // set the selected accounts
        for(sitesVFReContracting.AccountWrapper myAccountWrapper : accounts) {
        	myAccountWrapper.SelectedContactId = myContact.Id;
        }
        controller.setSelectedAccounts();
        
        // verify that accounts have been selected
        System.assertNotEquals(controller.SelectedAccounts.isEmpty(), true);
        
        // verify that terms exist
        System.assertNotEquals(controller.AvailableTerms.isEmpty(), true);
        for(sitesVFReContracting.TermWrapper term : controller.AvailableTerms) {
        	term.SelectedValue = '5';
        }
        
        controller.Submit();
        // verify that a contract was created
        List<GSOContract__c> contracts = [Select Id From GSOContract__c Where Account__c = : myAccount.Id];
        System.assertNotEquals(contracts.isEmpty(), true);
        
        // verify navigation
        controller.first();
        controller.next();
        controller.previous();
        controller.last();
        controller.goToStep1();
        controller.goToStep2();
        controller.goToStep3();
        System.assertEquals(controller.hasNext, false);
       	System.assertEquals( controller.hasPrevious, false);
        
        test.stopTest();
    }
}