objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Venere property</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Super_Region__c</fullName>
        <label>Super Region</label>
        <referenceTo>Super_Region__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Contract_Checklist__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contract Checklists</relationshipLabel>
        <relationshipName>Contract_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Set_up_EVC__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates to if hotel is to be set up with EVC.</description>
        <inlineHelpText>Check this box if you want the hotel to be set up with EVC (Expedia Virtual Card).</inlineHelpText>
        <label>Set up EVC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Set_up_Expedia_Pay__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field indicates if a property is to be set up on Expedia pay</description>
        <inlineHelpText>Check this box if you want the hotel to be set up with an Expedia Pay account.</inlineHelpText>
        <label>Set up Expedia Pay</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Approval Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Load - Rate Sheet Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Load - Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Returned to MM/MC-See Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Returned to Loading Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected - Returned to Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requested ID&apos;s(Vendor or Expedia ID)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loading Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Ready for QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Loading Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional Inventory Load - Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Load Additional Inventory</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contract Checklist</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Contract Checklist Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EIDRequestExtension_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class EIDRequestExtension_Test {

    static testMethod void myUnitTest() {
        
        Super_Region__c objSuperRegion = [Select Id From Super_Region__c where Name = 'LATAM'];
    	// create account
    	Account objAccount = (Account)SmartFactory.createSObject('Account');
    	objAccount.Super_Region__c = objSuperRegion.Id;
    	insert objAccount;
    	
    	// create contract checklist
    	Contract_Checklist__c objContractChecklist = (Contract_Checklist__c)SmartFactory.createSObject('Contract_Checklist__c');
    	objContractChecklist.Status__c = 'Requested ID\'s(Vendor or Expedia ID)';
    	objContractChecklist.Set_up_Expedia_Pay__c = true;
    	objContractChecklist.Set_up_EVC__c = true;
    	objContractChecklist.Account__r = objAccount;
    	insert objContractChecklist;

		test.startTest();
		
		Apexpages.currentPage().getParameters().put('Id', objContractChecklist.Id);
        EIDRequestExtension extEIDRequest = new EIDRequestExtension();
		
		extEIDRequest.Save();
		extEIDRequest.Cancel();
		
		test.stopTest();
    }
}