objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Venere property</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

objects/Contract_Checklist__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contract Checklists</relationshipLabel>
        <relationshipName>Contract_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Checklist_Type__c</fullName>
        <label>Checklist Type</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New-Reactivation/GDS to ESR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate Sheet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SBP Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic Accounts – New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic Accounts – Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent - New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent - Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specialty Lodging - New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specialty Lodging - Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advanced Deposit Addendum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS Standard Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS Show Ticket Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS non Standard Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS Standard Hawaii</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS Rate Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS Renewal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Approval Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Load - Rate Sheet Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Load - Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Returned to MM/MC-See Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Returned to Loading Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected - Returned to Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requested ID&apos;s(Vendor or Expedia ID)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loading Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Ready for QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Loading Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional Inventory Load - Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Load Additional Inventory</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contract Checklist</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Contract Checklist Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ContractChecklistTrigger_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class ContractChecklistTrigger_Test {

    static testMethod void myUnitTest() {
      
      Account testAccount = new Account(Name = 'Test Account 1');
      
      insert testAccount;
      Contract_Checklist__c checklist = new Contract_Checklist__c(Account__c = testAccount.Id
                                                                 ,Checklist_Type__c = 'Test'
                                                                 ,Status__c = 'New');
      
      insert checklist;
      
      checklist.Status__c = 'Closed';
      test.startTest();
      update checklist;
      
    }
}