objects/Case_Team__c.object
<CustomObject>
    <description>Used to look up the case record type and team based on the incoming email address</description>
    <fields>
        <fullName>Email_Service_Address__c</fullName>
        <description>Email Service Address used to lookup the record type</description>
        <inlineHelpText>Email Service Address used to lookup the record type</inlineHelpText>
        <label>Email Service Address</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CaseTeam</label>
    <nameField>
        <label>Case Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CaseTeams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CaseTeamClass.cls
public with sharing class CaseTeamClass {

	public static Case_Team__c FindByEmail(String email) {
		// dynamically build query
		List<SoqlBuilder.Condition> conditions = new List<SoqlBuilder.Condition>();
		conditions.add(new SoqlBuilder.Condition('Email_Service_Address__c', String.escapeSingleQuotes(email)));

		String objectName = Case_Team__c.sObjectType.getDescribe().getName();
		List<SObject> listObjects = SoqlBuilder.ExecuteSelectQuery(objectName, conditions);
		
		if(listObjects.isEmpty() == false) {
			return (Case_Team__c)listObjects.get(0);
		}
		
		return null;
	}
}