objects/Case.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <description>Identifies team case is assinged to</description>
        <label>Team</label>
        <picklist>
            <picklistValues>
                <fullName>Air CPR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Air Fulfillment Ops</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Airline Debit Memos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banking Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Breakage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commissions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance &amp; Recovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Loading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC Help</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Destination services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ecom NewTrade Product Creation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ecom NewTrade Rollout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ecom NewTrade TSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EID/VID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elite Plus VIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EQC Help</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expedia Pay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expedia Virtual Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fare Filing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FinOps EVC Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geography</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GSO - Athens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GSO - Dallas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GSO - Kuala Lumpur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GSO - Prague</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GSO - Springfield</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotel Content</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Support_Request</fullName>
        <active>true</active>
        <businessProcess>Support Request</businessProcess>
        <description>Used by GSO team to handle support requests from business teams</description>
        <label>Support Request</label>
    </recordTypes>
</CustomObject>

objects/Case_Team__c.object
<CustomObject>
    <description>Used to look up the case record type and team based on the incoming email address</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>CaseTeams</relationshipLabel>
        <relationshipName>CaseTeams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Record_Type_Developer_Name__c</fullName>
        <description>Developer name of the record type</description>
        <inlineHelpText>Developer name of the record type</inlineHelpText>
        <label>Record Type Developer Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <description>Team</description>
        <inlineHelpText>Team</inlineHelpText>
        <label>Team</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CaseTeam</label>
    <nameField>
        <label>Case Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CaseTeams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Language__c.object
<CustomObject>
    <label>Language</label>
    <nameField>
        <label>Language Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EmailServicesHandler.cls
global class EmailServicesHandler implements Messaging.InboundEmailHandler {
    
    global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope) {
    Messaging.InboundEmailResult result = new Messaging.InboundEmailresult();
       
    system.debug('*** EmailServicesHandler => envelope.toAddress = ' + envelope.toAddress + ' ***');      
    CaseClass objCase = new CaseClass();
    
    try{
	    // Lookup the record type and team based on the envelope.toAddress
	    Case_Team__c caseTeam = CaseTeamClass.FindByEmail(envelope.toAddress);
	    
	    if(caseTeam != null) {
			// only generate a case for active case teams
			if(caseTeam.Active__c == True) {
		      // Look at To envelope.toAddress and call appropriate case, passing correct record type
		      objCase.processEmail(email, caseTeam.Record_Type_Developer_Name__c, caseTeam.Team__c, caseTeam.Language__c);
			}        
	    }else {
	      // email not handled so create a
	      //Support Request
	      objCase.processEmail(email, 'Support_Request', null, null);
	    }
    }catch(Exception ex) {
    	Id exId = ExceptionClass.InsertException(ex);
    	EmailUtilities.saveAttachmentsToException(email, exId);
    }

    system.debug('***EmailServicesHandler => Before Return***');    
    return result;  
  }

}