objects/Exception__c.object
<CustomObject>
    <description>Used to store and track exceptions</description>
    <fields>
        <fullName>Line_Number__c</fullName>
        <description>Line Number</description>
        <label>Line Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>Exception message</description>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <description>Stack Trace</description>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type_Name__c</fullName>
        <description>Type of exception</description>
        <label>Type Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Exception</label>
    <nameField>
        <displayFormat>EX-{000000}</displayFormat>
        <label>Exception Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ExceptionClass.cls
public class ExceptionClass {
    
    public static Id InsertException(Exception exc) {
 		// save exception
		return CreateException(exc);
    }
    
    /////// Private Methods
    
    private static Id CreateException(Exception exc) {
 		// save exception
		Exception__c ex = new Exception__c();
		ex.Message__c = exc.getMessage();
		ex.Type_Name__c = exc.getTypeName();
		ex.Line_Number__c = exc.getLineNumber();
		ex.Stack_Trace__c = exc.getStackTraceString();
		
		insert ex;

		return ex.Id;
    }
    
}