objects/GSO_Contract_Submission__c.object
<CustomObject>
    <fields>
        <fullName>PSG_User__c</fullName>
        <description>PSG User</description>
        <label>PSG User</label>
        <referenceTo>PSG_User__c</referenceTo>
        <relationshipLabel>GSO Contract Submissions (PSG User)</relationshipLabel>
        <relationshipName>Re_Contract_Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GSO Contract Submission</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Submission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GSO Contract Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GSOContract__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Comment__c</fullName>
        <description>Approval Comment</description>
        <label>Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>Status of approval process</description>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approved_By__c</fullName>
        <description>Approved By</description>
        <label>Approved By</label>
        <referenceTo>PSG_User__c</referenceTo>
        <relationshipLabel>GSO Contracts</relationshipLabel>
        <relationshipName>GSO_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GSO_Contract_Submission__c</fullName>
        <description>GSO Contract Submission</description>
        <label>GSO Contract Submission</label>
        <referenceTo>GSO_Contract_Submission__c</referenceTo>
        <relationshipLabel>GSO Contracts</relationshipLabel>
        <relationshipName>GSOContracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>GSO Contract</label>
    <nameField>
        <displayFormat>GC-{000000}</displayFormat>
        <label>GSO Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GSO Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GSOContract_Term__c.object
<CustomObject>
    <description>Junction object to allow many to many relationship between Contracts and Terms</description>
    <fields>
        <fullName>GSOContract__c</fullName>
        <label>GSOContract</label>
        <referenceTo>GSOContract__c</referenceTo>
        <relationshipName>GSOContract_Terms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>GSO Contract Term</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>GSO Contract Term Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GSO Contract Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PSG_User__c.object
<CustomObject>
    <description>List of Users who are active in PSG and not active in GSO who need to share information with GSO Users.</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>PSG User</label>
    <nameField>
        <label>PSG User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PSG Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/sitesReContractingApproval.cls
public class sitesReContractingApproval {
	public List<GSOContract_Term__c > Terms {get; set;}
	public List<ContractWrapper> Contracts {get; set;}
	public List<GSO_Contract_Submission__c> Submissions {get; set;}
	public GSO_Contract_Submission__c Submission {get; set;}
	public Boolean SelectAllCheckboxes {get; set;}
	public String ApprovalComment {get; set;}
	public String ApprovalStatus {get; set;}
	public Boolean Completed {get; set;}
	public Id SubmissionId {get; set;}

    public PSG_User__c PSGUser {
    	get {
    		if(PSGUser == null) {
		        String approver = Apexpages.currentPage().getParameters().get('MM');
		        PSGUser = PSGUserClass.findByEmail(approver);
    		}
    		return PSGUser;
    	}
    	set;
	}
	
	///// Wrapper class for GSO Contracts
	public class ContractWrapper {
		public GSOContract__c objGSOContract {get; set;}
		public Boolean Selected {get; set;}
		
		public ContractWrapper(GSOContract__c myContract) {
			objGSOContract = myContract;
			Selected = true;
		}
	}// End of ContractWrapper class
	
	public sitesReContractingApproval() {
		if(PSGUser != null) {
			Submissions = getSubmissions();
		} 
		
		// get submission
		Submission = getSubmission();
		
		if(Submission != null) {
			// get contracts
			Contracts = getContracts();

			// get terms			
			if(Contracts.isEmpty() == false) {
				Terms = getTerms(Contracts.get(0).objGSOContract.Id);
			}
		}
		
		SelectAllCheckboxes = true;
		Completed = false;
	}
	
	public PageReference Submit() {
		
		if(ApprovalStatus == null) {
			Apexpages.addMessage(new Apexpages.Message(Apexpages.Severity.Error, 'Please select an approval status.'));
		}else {
			ApproveReject();
		}
		return Apexpages.currentPage();
	}
	
	public PageReference Step1() {
    	PageReference p = Page.ReContractingApprovalStep1;
    	p.setRedirect(true);
		p.getParameters().put('MM', PSGUser.Email__c);
		return p;
	}

    public PageReference VerifyAuthentication() {
        // User has not been authenticated redirect to the authentication page
        if(PSGUserClass.isAuthenticatedUser(PSGUser) == false) { 
            return Page.ReContractingAuthentication;
        }

        // User has been authenticated
        return null;
    }
    
    ///// Private Methods
    private List<GSO_Contract_Submission__c> getSubmissions() {
    	return GSOContractSubmissionClass.getPendingApprovals(this.PSGUser.Email__c);
    }
    
	private GSO_Contract_Submission__c getSubmission() {
		GSO_Contract_Submission__c mySubmission;
		
		try{
			Id sId = (SubmissionId != null ? SubmissionId : Apexpages.currentPage().getParameters().get('Id'));
			// get submission
			system.debug('>>>>>> sitesReContractingApproval getSubmission sid: ' + sId);
			mySubmission = GSOContractSubmissionClass.findById(sId);
		}catch(Exception ex)
		{
			system.debug('>>>>>> sitesReContractingApproval getSubmission exception: ' + ex);
		}
		
		return mySubmission;
	}
	
	private List<ContractWrapper> getContracts() {
		List<ContractWrapper> gsoContracts = new List<ContractWrapper>();
		
		// get list of contracts
		for(GSOContract__c myContract : GSOContractClass.findBySubmissionId(Submission.Id)) {
			gsoContracts.add(new ContractWrapper(myContract));				
		}
		
		return gsoContracts;
	}
	
	private List<GSOContract_Term__c > getTerms(Id contractId) {
		// get list of terms
		return GSOContractTermClass.findByContractId(contractId);
	}
	
	private void ApproveReject() {
		List<GSOContract__c> gsoContracts = new List<GSOContract__c>();
		
		// set approval status and comments for each selected hotel
		for(ContractWrapper myContract : Contracts) {
			if(myContract.Selected == true) {
				myContract.objGSOContract.Approved_By__c = psgUser.Id;
				myContract.objGSOContract.Approval_Status__c = ApprovalStatus;
				myContract.objGSOContract.Approval_Comment__c = ApprovalComment;
				
				gsoContracts.add(myContract.objGSOContract);
			}
		}
		
		try{
			update gsoContracts;
			Completed = true;
		}catch(Exception ex) {
			Apexpages.addMessages(ex);
		}
	}
	
}