objects/GSO_Contract_Submission__c.object
<CustomObject>
    <label>GSO Contract Submission</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Submission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GSO Contract Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GSOContract__c.object
<CustomObject>
    <fields>
        <fullName>GSO_Contract_Submission__c</fullName>
        <description>GSO Contract Submission</description>
        <label>GSO Contract Submission</label>
        <referenceTo>GSO_Contract_Submission__c</referenceTo>
        <relationshipLabel>GSO Contracts</relationshipLabel>
        <relationshipName>GSOContracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>GSO Contract</label>
    <nameField>
        <displayFormat>GC-{000000}</displayFormat>
        <label>GSO Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GSO Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GSOContract_Term__c.object
<CustomObject>
    <description>Junction object to allow many to many relationship between Contracts and Terms</description>
    <fields>
        <fullName>GSOContract__c</fullName>
        <label>GSOContract</label>
        <referenceTo>GSOContract__c</referenceTo>
        <relationshipName>GSOContract_Terms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <referenceTo>Term__c</referenceTo>
        <relationshipName>GSOContract_Terms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>GSO Contract Term</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>GSO Contract Term Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GSO Contract Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Term__c.object
<CustomObject>
    <description>Commercial Terms for re-contracting</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Commercial Term Description</description>
        <inlineHelpText>Commercial Term Description</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Term</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Term Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GSOContractTermClass_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class GSOContractTermClass_Test {

    static testMethod void myUnitTest() {
    	// create submission
    	GSO_Contract_Submission__c mySubmission = new GSO_Contract_Submission__c();
    	insert mySubmission;
    	
        // create contract
        GSOContract__c myContract = new GSOContract__c(GSO_Contract_Submission__c = mySubmission.Id);
        insert myContract;
        
        // create terms
	    Term__c[] terms = new Term__c[] {
	      new Term__c(Description__c = 'Term 1'),
		    new Term__c(Description__c = 'Term 2'),
		    new Term__c(Description__c = 'Term 3')
		  };
        insert terms;
        
        // create contract terms
        GSOContract_Term__c[] contractTerms = new GSOContract_Term__c[] {
        	new GSOContract_Term__c(Value__c= '1', Term__c = terms.get(0).Id, GSOContract__c = myContract.Id),
        	new GSOContract_Term__c(Value__c= '2', Term__c = terms.get(1).Id, GSOContract__c = myContract.Id),
        	new GSOContract_Term__c(Value__c= '3', Term__c = terms.get(2).Id, GSOContract__c = myContract.Id)
        };
        insert contractTerms;
        
        test.startTest();
        
        List<GSOContract_Term__c> results = GSOContractTermClass.findByContractId(myContract.Id);
        system.assertEquals(results.size(), contractTerms.size());
        
        test.stopTest();
    }
}