objects/GSO_Contract_Submission__c.object
<CustomObject>
    <fields>
        <fullName>Approver_Email__c</fullName>
        <label>Approver Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contracts_Pending_Approval__c</fullName>
        <description>Contracts Pending Approval</description>
        <label>Contracts Pending Approval</label>
        <summaryFilterItems>
            <field>GSOContract__c.Approval_Status__c</field>
            <operation>equals</operation>
            <value>Pending Approval</value>
        </summaryFilterItems>
        <summaryForeignKey>GSOContract__c.GSO_Contract_Submission__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>PSG_User__c</fullName>
        <description>PSG User</description>
        <label>PSG User</label>
        <referenceTo>PSG_User__c</referenceTo>
        <relationshipLabel>GSO Contract Submissions (PSG User)</relationshipLabel>
        <relationshipName>Re_Contract_Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GSO Contract Submission</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Submission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GSO Contract Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GSOContract__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if contract requires approval before being sent to ORT</description>
        <label>Approval Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>Status of approval process</description>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GSO_Contract_Submission__c</fullName>
        <description>GSO Contract Submission</description>
        <label>GSO Contract Submission</label>
        <referenceTo>GSO_Contract_Submission__c</referenceTo>
        <relationshipLabel>GSO Contracts</relationshipLabel>
        <relationshipName>GSOContracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>GSO Contract</label>
    <nameField>
        <displayFormat>GC-{000000}</displayFormat>
        <label>GSO Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GSO Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PSG_User__c.object
<CustomObject>
    <description>List of Users who are active in PSG and not active in GSO who need to share information with GSO Users.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates if user is active is PSG Salesforce</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>PSG User</label>
    <nameField>
        <label>PSG User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PSG Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GSOContractSubmissionClass_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class GSOContractSubmissionClass_Test {

    static testMethod void myUnitTest() {
    	String approverEmail = 'gsotestap@expedia.com';
    	
    	// create psg user
    	PSG_User__c myPSGUser = new PSG_User__c(Name= 'test user', Email__c= 'gsotest@expedia.com', Active__c= true );
    	insert myPSGUser;
    	
    	// create submission
		GSO_Contract_Submission__c submission = new GSO_Contract_Submission__c(PSG_User__c= myPSGUser.Id, Approver_Email__c= approverEmail);
		insert submission;
		
		// create contract
		GSOContract__c myContract = new GSOContract__c(GSO_Contract_Submission__c= submission.Id, Approval_Status__c= 'Pending Approval', Approval_Required__c= true);
		insert myContract;
		
		submission = [Select Id, PSG_User__c, Approver_Email__c, Contracts_Pending_Approval__c From GSO_Contract_Submission__c Where Id = : submission.Id];
		system.assertEquals(submission.Contracts_Pending_Approval__c, 1);
		
		test.startTest();
		
		GSO_Contract_Submission__c result = GSOContractSubmissionClass.findById(submission.Id);
		system.assertEquals(result.Id, submission.Id);
		
		List<GSO_Contract_Submission__c> results = GSOContractSubmissionClass.getPendingApprovals(approverEmail);
		system.assertEquals(results.size(), submission.Contracts_Pending_Approval__c);
		
		test.stopTest();
    }
}