objects/GSO_Contract_Submission__c.object
<CustomObject>
    <fields>
        <fullName>Approver_Email__c</fullName>
        <label>Approver Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contracts_Pending_Approval__c</fullName>
        <description>Contracts Pending Approval</description>
        <label>Contracts Pending Approval</label>
        <summaryFilterItems>
            <field>GSOContract__c.Approval_Status__c</field>
            <operation>equals</operation>
            <value>Pending Approval</value>
        </summaryFilterItems>
        <summaryForeignKey>GSOContract__c.GSO_Contract_Submission__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>PSG_User__c</fullName>
        <description>PSG User</description>
        <label>PSG User</label>
        <referenceTo>PSG_User__c</referenceTo>
        <relationshipLabel>GSO Contract Submissions (PSG User)</relationshipLabel>
        <relationshipName>Re_Contract_Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GSO Contract Submission</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Submission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GSO Contract Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GSOContract__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>GSO Contracts</relationshipLabel>
        <relationshipName>GSOContracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expedia_Hotel_Id__c</fullName>
        <formula>Account__r.Expedia_Hotel_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expedia Hotel Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GSO_Contract_Submission__c</fullName>
        <description>GSO Contract Submission</description>
        <label>GSO Contract Submission</label>
        <referenceTo>GSO_Contract_Submission__c</referenceTo>
        <relationshipLabel>GSO Contracts</relationshipLabel>
        <relationshipName>GSOContracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>GSO Contract</label>
    <nameField>
        <displayFormat>GC-{000000}</displayFormat>
        <label>GSO Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GSO Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PSG_User__c.object
<CustomObject>
    <description>List of Users who are active in PSG and not active in GSO who need to share information with GSO Users.</description>
    <label>PSG User</label>
    <nameField>
        <label>PSG User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PSG Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GSOContractSubmissionClass.cls
public with sharing class GSOContractSubmissionClass {
	
	public static GSO_Contract_Submission__c findById(Id submissionId) {
		String myFields = '*, PSG_User__r.Name';
		
		// build where clause
    	List<SoqlBuilder.Condition> conditions = new List<SoqlBuilder.Condition>();
    	conditions.add(new SoqlBuilder.Condition('Id', submissionId));
    	
		List<GSO_Contract_Submission__c> submissions = findBy(myFields, conditions, null, null);
		if(submissions.isEmpty() == false) {
			return submissions.get(0);
		}

		return null;
	}

	public static List<GSO_Contract_Submission__c> getPendingApprovals(string approverEmail) {
		String myFields = '*, PSG_User__r.Name, (Select Account__r.Name, Account__r.Expedia_Hotel_Id__c From GSOContracts__r)';
		
		// build where clause
    	List<SoqlBuilder.Condition> conditions = new List<SoqlBuilder.Condition>();
    	conditions.add(new SoqlBuilder.Condition('Contracts_Pending_Approval__c', '0', '>'));
    	conditions.add(new SoqlBuilder.Condition('Approver_Email__c', approverEmail));
    	
		List<GSO_Contract_Submission__c> submissions = findBy(myFields, conditions, null, 'CreatedDate');

		return submissions;
	}
	

	//// Private methdos
	
    private static List<GSO_Contract_Submission__c> findBy(String myFields, List<SoqlBuilder.Condition> conditions, String conditionLogic, String orderBy) {
		return SoqlBuilder.ExecuteSelectQuery(myFields, 'GSO_Contract_Submission__c', conditions, conditionLogic, orderBy);
    }
}