objects/GSOContract__c.object
<CustomObject>
    <label>GSO Contract</label>
    <nameField>
        <displayFormat>GC-{000000}</displayFormat>
        <label>GSO Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GSO Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GSOContract_Term__c.object
<CustomObject>
    <description>Junction object to allow many to many relationship between Contracts and Terms</description>
    <fields>
        <fullName>GSOContract__c</fullName>
        <label>GSOContract</label>
        <referenceTo>GSOContract__c</referenceTo>
        <relationshipName>GSOContract_Terms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <referenceTo>Term__c</referenceTo>
        <relationshipName>GSOContract_Terms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>GSO Contract Term</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>GSO Contract Term Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GSO Contract Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Term__c.object
<CustomObject>
    <description>Commercial Terms for re-contracting</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Commercial Term Description</description>
        <inlineHelpText>Commercial Term Description</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Term</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Term Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GSOContractTermClass.cls
public with sharing class GSOContractTermClass {
	
	public static List<GSOContract_Term__c> findByContractId(Id contractId) {
		// build where clause
    	List<SoqlBuilder.Condition> conditions = new List<SoqlBuilder.Condition>();
    	conditions.add(new SoqlBuilder.Condition('GSOContract__c', contractId));
    	
		return findBy('*, Term__r.Description__c', conditions, null, null);
	}

	//// Private methdos
	
    private static List<GSOContract_Term__c> findBy(String myFields, List<SoqlBuilder.Condition> conditions, String conditionLogic, String orderBy) {
		return SoqlBuilder.ExecuteSelectQuery(myFields, 'GSOContract_Term__c', conditions, conditionLogic, orderBy);
    }

}