objects/Guest__c.object
<CustomObject>
    <description>Guest Object</description>
    <fields>
        <fullName>Arrival_Date__c</fullName>
        <label>Arrival Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Guests</relationshipLabel>
        <relationshipName>Guests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Difference_Absorbed_By__c</fullName>
        <label>Difference Absorbed By</label>
        <picklist>
            <picklistValues>
                <fullName>Cancellation - Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation - Natural Disaster</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation-Front Line CS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decision Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eviivo Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expedia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shared Hotel &amp; Expedia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotel Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Original Rate Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Walk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Walk with Quest Compensation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>New_Expedia_Booking_ID__c</fullName>
        <label>New Expedia Booking ID</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>New_Vendor__c</fullName>
        <label>New Hotel</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Guests</relationshipLabel>
        <relationshipName>Guests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Nights__c</fullName>
        <formula>Check_Out_Date__c  -  Arrival_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Number of Nights</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Relocation_Cost__c</fullName>
        <formula>IF(Booking_Net_Difference__c&lt;0,&quot;0&quot;,TEXT(ROUND(Booking_Net_Difference__c,2)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This field sets the Booking Net Difference field to &quot;0&quot; if the difference is less than &quot;0&quot;. If more than &quot;0&quot;, it rounds the number to 2 decimal places. Used for internal calculations.</inlineHelpText>
        <label>Relocation Cost</label>
        <type>Text</type>
    </fields>
    <label>Guest</label>
    <nameField>
        <label>Guest  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/GuestClass.cls
public class GuestClass {
	
	public Id CaseId {get; set;}
	
	public List<Guest__c> getGuestList() {
		List<Guest__c> guests = [SELECT Name, 
									Id, 
									Arrival_Date__c, 
									Number_of_Nights__c, 
									New_Expedia_Booking_ID__c, 
									Relocation_Cost__c, 
									Difference_absorbed_by__c, 
									New_Vendor__r.Id, 
									New_Vendor__r.Name 
									FROM Guest__c g, g.New_Vendor__r, g.Case__r 
									WHERE Case__r.Id = : CaseId];
									
		return guests;
	}
}