objects/Term__c.object
<CustomObject>
    <description>Commercial Terms for re-contracting</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Date the commercial term expires. Leave blank to keep the term open indefinitely.</description>
        <inlineHelpText>Date the commercial term expires. Leave blank to keep the term open indefinitely.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <description>Order in which the terms are displayed in the wizard</description>
        <inlineHelpText>Order in which the terms are displayed in the wizard</inlineHelpText>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Term</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Term Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Term_Value__c.object
<CustomObject>
    <fields>
        <fullName>Default_Value__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Default Value</description>
        <label>Default Value</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <description>Sort Order</description>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <referenceTo>Term__c</referenceTo>
        <relationshipLabel>Term Values</relationshipLabel>
        <relationshipName>Term_Values</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Term Value</label>
    <nameField>
        <label>Term Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Term Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TermClass.cls
public with sharing class TermClass {
	
	public static List<Term__c> findByDate(Date beginDate, Date endDate) {
		// fields to retrieve
		String myFields = '*, (Select Name, Default_Value__c From Term_Values__r order by Sort_Order__c)';
		
		// build where clause
    	List<SoqlBuilder.Condition> conditions = new List<SoqlBuilder.Condition>();
    	conditions.add(new SoqlBuilder.Condition('End_Date__c', null));
    	conditions.add(new SoqlBuilder.Condition('End_Date__c', string.valueOf(beginDate), '>='));
    	conditions.add(new SoqlBuilder.Condition('End_Date__c', string.valueOf(endDate), '<='));
    	
		List<Term__c> terms = findBy(myFields, conditions, '{0} OR ({1} AND {2})', 'Sort_Order__c');

		return terms;
	}
	

	//// Private methdos
	
    private static List<Term__c> findBy(String myFields, List<SoqlBuilder.Condition> conditions, String conditionLogic, String orderBy) {
		return SoqlBuilder.ExecuteSelectQuery(myFields, 'Term__c', conditions, conditionLogic, orderBy);
    }
}